### ISSUE TITLE
Proposed Ammendment Chapter 2 reference to "Portable Usage \& Changing the Configuration"

### ISSUE THREAD

**Issue by PaulANormanNZ** [TeXworks/manual#3]
Can't upload files, so putting information here.

In:  installation.tex
Just before section "2.1 Under Windows"

Proposed new text paragraph insertion :

`For details on portable usage, and changing local configuration locations, please see the section Portable Usage \& Changing the Configuration -- section \ref{sec.portable_configuration} (on page \pageref{sec.portable_configuration}).`

**Comment by PaulANormanNZ** [comment]
Would look like this:
![new_2-installation](https://user-images.githubusercontent.com/457267/61258230-aed4f300-a7c8-11e9-8430-c771922405cd.png)

**Comment by stloeffler** [comment]
Hi Paul. I think you can implement changes directly by navigating to the file on GitHub (https://github.com/TeXworks/manual/blob/master/src/en/installation.tex) and click on the pen icon (right next to "Raw", "Blame", "History"). That should tell you something about not having write access and therefore creating a fork, but without going into the technical details, it should work nevertheless to edit the file and "Propose file change". That would allow me to directly transfer your changes and give you proper attribution as well.

**Comment by PaulANormanNZ** [comment]
Ok Stefan,
I'll have a look into that.
Thanks,
Paul

**Comment by stloeffler** [comment]
Thanks for the changes. I merged them into the main code.
